# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalculateIsochrones
                                 A QGIS plugin
 This plugin calculates a surface representing all the points reachable from a starting point in a specific time.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-28
        copyright            : (C) 2025 by Yolanda Seifert
        email                : yolanda.seifert@gmx.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CalculateIsochrones class from file CalculateIsochrones.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .calculate_isochrones import CalculateIsochrones
    return CalculateIsochrones(iface)
