# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalculateIsochrones
                                 A QGIS plugin
 This plugin calculates a surface representing all the points reachable from a starting point in a specific time.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-28
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Yolanda Seifert
        email                : yolanda.seifert@gmx.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox
from qgis.core import QgsProject, QgsVectorLayer, QgsVectorFileWriter, QgsCoordinateTransform, QgsCoordinateReferenceSystem
import qgis.utils
from qgis.gui import QgsMapToolEmitPoint



# Initialize Qt resources from file resources.py
from .resources import *
from .IGNCapabilities import IGNCapabilities
from .IGNRequest import IGNRequest
# Import the code for the dialog
from .calculate_isochrones_dialog import CalculateIsochronesDialog
import os.path


class CalculateIsochrones:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.canvas = iface.mapCanvas()
        self.selected_crs = "EPSG:4326" # take as default
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CalculateIsochrones_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CalculateIsochrones')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CalculateIsochrones', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/calculate_isochrones/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Calculate Isochrone Polygon'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&CalculateIsochrones'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(self.dlg, "Select   output file","",'*.gpkg')
        self.dlg.lineEditOutputFile.setText(filename)

    def save_as_gpkg(self, layer, output_path):
        """Save a vector layer as a geopackage

        Args:
            layer (QgsVectorLayer): layer to be saved
            output_path (str): path where layer is to be saved
        """
        context = QgsProject.instance().transformContext()
        name = layer.name()
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.layerName = name
        options.fileEncoding = layer.dataProvider().encoding()
        options.driverName = "GPKG"
        QgsVectorFileWriter.writeAsVectorFormatV3(layer, output_path, context, options)

    def populate_comboBoxes(self):
        # clear the combo boxes from previous runs
        self.dlg.comboBoxType.clear()
        self.dlg.comboBoxTimeUnit.clear()
        self.dlg.comboBoxDistanceUnit.clear()
        self.dlg.comboBoxProfile.clear()
        self.dlg.comboBoxDirection.clear()
        self.dlg.comboBoxCRS.clear()
        # populate all other combo boxes depending on selected resource and capabilities
        ign_capabilities = IGNCapabilities("https://data.geopf.fr/navigation/getcapabilities")
        resource = self.dlg.comboBoxResource.currentText()
        ign_capabilities.populate_comboBox(resource, 'costType', self.dlg.comboBoxType)
        ign_capabilities.populate_comboBox(resource, 'timeUnit', self.dlg.comboBoxTimeUnit)
        ign_capabilities.populate_comboBox(resource, 'distanceUnit', self.dlg.comboBoxDistanceUnit)
        ign_capabilities.populate_comboBox(resource, 'profile', self.dlg.comboBoxProfile)
        ign_capabilities.populate_comboBox(resource, 'direction', self.dlg.comboBoxDirection)
        ign_capabilities.populate_comboBox(resource, 'projection', self.dlg.comboBoxCRS)

    def show_help(self):
        print("Help button clicked")
        qgis.utils.showPluginHelp()

    def select_coordinates(self):
        """select coordinates of a point by mouse clicking on the map
        """
        self.pointTool = QgsMapToolEmitPoint(self.canvas)
        self.pointTool.canvasClicked.connect(self.display_point)
        # activate the tool
        self.canvas.setMapTool(self.pointTool)

    def display_point(self, pointTool ): 
        """display selected point in lineEdit and transform to selected CRS

        Args:
            pointTool (QgsPointXY): point selected by mouse click
        """
        src_crs = self.canvas.mapSettings().destinationCrs()
        dest_crs = QgsCoordinateReferenceSystem(self.selected_crs)
        print(self.selected_crs)
        xform = QgsCoordinateTransform(src_crs, dest_crs, QgsProject.instance())
        geo_point = xform.transform(pointTool)
        self.dlg.lineEditStartingPoint.setText(f"{geo_point.x():.6f}, {geo_point.y():6f}")
        self.canvas.unsetMapTool(self.pointTool)

    def _update_crs(self):
        self.selected_crs = self.dlg.comboBoxCRS.currentText()

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = CalculateIsochronesDialog()
            self.dlg.pushButtonOutputFile.clicked.connect(self.select_output_file)

        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBoxResource.clear()
        # Populate the comboBox with names of all the resources
        self.dlg.comboBoxResource.addItems(["bdtopo-pgr", "bdtopo-valhalla", "pgr_sgl_r100_all"])
        self.dlg.comboBoxResource.activated.connect(self.populate_comboBoxes)
        self.dlg.comboBoxCRS.activated.connect(self._update_crs)
        self.dlg.pushButtonHelp.clicked.connect(self.show_help)
        self.dlg.pushButtonCoordinates.clicked.connect(self.select_coordinates)
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()

        # See if OK was pressed
        if result:
            # get values of the elements
            resource = self.dlg.comboBoxResource.currentText()
            starting_point = self.dlg.lineEditStartingPoint.text()
            cost_type = self.dlg.comboBoxType.currentText()
            cost_value = self.dlg.lineEditCostValue.text()
            time_unit = self.dlg.comboBoxTimeUnit.currentText()
            dist_unit = self.dlg.comboBoxDistanceUnit.currentText()
            profile = self.dlg.comboBoxProfile.currentText()
            direction = self.dlg.comboBoxDirection.currentText()
            crs = self.dlg.comboBoxCRS.currentText()
            constraints = self.dlg.textEditConstraints.toPlainText()

            # do request with elements
            ign_request = IGNRequest(resource, 
                                     starting_point,
                                     cost_value, 
                                     costType=cost_type,
                                     profile=profile, 
                                     timeUnit=time_unit,
                                     distanceUnit=dist_unit, 
                                     direction=direction, 
                                     crs=crs,
                                     constraints=constraints)
            output_geojson = ign_request.do_request()
            if output_geojson == None or output_geojson == 'null': # handle case where request unsuccessful
                QMessageBox.critical(None, "Failed to calculate",'No valid Response from Geoportal, possibly caused by unrealistic (to small or big) values.') 
                return
            # add layer to qgis instance
            layer = QgsVectorLayer(output_geojson, "isochrone_layer", "ogr")
            QgsProject.instance().addMapLayer(layer)

            # save geopackage layer to path selected by user
            out_path = self.dlg.lineEditOutputFile.text()
            self.save_as_gpkg(layer, out_path)
